services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d docsign']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - asign_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: asign_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asign_network

volumes:
  db:
    driver: local

networks:
  asign_network:
    driver: bridge
